## Now You Code 2: Syracuse Crime Data

In this second now you code you will explore the plot.ly engine in detail using Syracuse, NY FBI crime data.

In [1]:
import plotly.plotly as py    
import plotly.graph_objs as go  
import cufflinks as cf
import pandas as pd

In [2]:
crime = pd.read_csv('https://raw.githubusercontent.com/mafudge/datasets/master/crime/syracuse-crime-data-1985-2012.csv')
crime.sample(10)

,Year,Months,Population,Violent crime total,Murder and nonnegligent Manslaughter,Forcible rape,Robbery,Aggravated assault,Property crime total,Burglary,...,Violent Crime rate,Murder and nonnegligent manslaughter rate,Forcible rape rate,Robbery rate,Aggravated assault rate,Property crime rate,Burglary rate,Larceny-theft rate,Motor vehicle theft rate,Unnamed: 21
4,1989,12,154960,1360,13,113,488,746,10290,3502,...,877.6,8.4,72.9,314.9,481.4,6640.4,2259.9,4016.5,364.0,NaN
9,1994,12,163374,1234,16,58,582,578,9409,2945,...,755.3,9.8,35.5,356.2,353.8,5759.2,1802.6,3476.7,479.9,NaN
23,2008,12,138211,1366,24,71,419,852,6165,1938,...,988.3,17.4,51.4,303.2,616.4,4460.6,1402.2,2695.2,363.2,NaN
21,2006,12,142062,1515,12,66,534,903,6677,1904,...,1066.4,8.4,46.5,375.9,635.6,4700.1,1340.3,2841.7,518.1,NaN
7,1992,12,165029,1512,13,85,645,769,10326,3023,...,916.2,7.9,51.5,390.8,466.0,6257.1,1831.8,4016.9,408.4,NaN
27,2012,12,145934,1372,14,75,454,829,5976,1896,...,940.2,9.6,51.4,311.1,568.1,4095.0,1299.2,2534.0,261.8,NaN
10,1995,12,159603,1467,18,84,633,732,9873,3048,...,919.2,11.3,52.6,396.6,458.6,6186.0,1909.7,3779.4,496.9,NaN
15,2000,12,147306,1565,18,47,452,1048,7565,1846,...,1062.4,12.2,31.9,306.8,711.4,5135.6,1253.2,3354.2,528.2,NaN
18,2003,12,145411,1383,17,44,477,845,7773,1975,...,951.1,11.7,30.3,328.0,581.1,5345.5,1358.2,3171.7,815.6,NaN
16,2001,12,147577,1562,15,42,567,938,7905,1810,...,1058.4,10.2,28.5,384.2,635.6,5356.5,1226.5,3519.5,610.5,NaN

In [3]:
# Make a line plot of population over the years, using cufflinks crime.iplot()
# set the titles on x "Year, Y "Population" and cart title " Syracuse Population" 
# TODO: replace the ???? with appropriate values to render the chart
crime.iplot(kind = 'scatter', x = 'Year', y = 'Population', title='Syracuse Population',xTitle='Year',yTitle='Population')

In [5]:
# Step 1:
# Now plot the same thing using plot.ly without cufflinks, again filling in the templates. Using plot.ly takes more effort but
# you have more control / flexibility over how the plots are rendered.
plot_data = [
    go.Scatter(x=crime['Year'], y=crime['Robbery rate'], mode="lines+markers", name="Robbery Rate", marker=dict(color='orange')),
    go.Scatter(x=crime['Year'], y=crime['Motor vehicle theft rate'], mode="lines+markers", name="Motor Vehicle Theft Rate", marker=dict(color='blue')),
]

py.iplot({ 'data': plot_data,
            'layout': {
               'title': 'Robbery Rate versus Motor Vehicle Theft Rate',
               'xaxis': {
                 'title': 'Year'},
               'yaxis': {
                'title': 'Rate'}
        }})

In [ ]:
# Step 2:
# Now create a line plot of "Robbery rate" versus "Motor vehicle theft rate" over time.
# NOTE: you will need two series in your plot_data

# Interactive Plots

Finally write a program to ask for a crime metric like "Robbery" / "Burglary" / "Manslaughter" etc as input, 
then renders a plot of that metric over time as output !

Note: check to make sure the entered crime metric is in the list of Pandas columns before you attempt to plot. 
It might be a good idea to print the column names before you plot.
if it is not you should print "That is not a crime metric"

## Step 3: Problem Analysis

Inputs:
* filename
* user input - crimes commited

Outputs:

* graph showing the crime over years 
* input error if crime is not on the list

Algorithm (Steps in Program):

* import statements plotly.ploty, plotly.graph_objs, cufflinks, pandas, and addressing warnings
* import the csv and assign as variable crime
* create a list of crimes based on column data. 
* while true to start a loop
    * user inputs the crime they want to view
    * if statment for if the user input is in the list of crimes
        * break to stop the loop and proceed
    * if statement for if they enter list
        * count = 1 to start a numbered list
        * for to start going through each line of the list
            * print the count and crime to add a displayed list row
            * increment the count
            * continue the loop
* else:
    * print statment indicating they haven't entered a valid crime
    * continue the loop
* assign the plot_data variable to display the graph

In [6]:
## Step 4: Write code here

## Step 4: Write code here
import plotly.plotly as py    
import plotly.graph_objs as go  
import cufflinks as cf
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

crime = pd.read_csv('https://raw.githubusercontent.com/mafudge/datasets/master/crime/syracuse-crime-data-1985-2012.csv')
crime_list = list(crime.columns.values[4:])

while True:
        user_input = input("Enter crime to track or type 'list' crimes list. Type 'quit' to exit: ")
        if user_input in crime_list:
            break
        if user_input == 'list':
            count = 1
            for crime_name in crime_list:
                print("%d: %s" % (count, crime_name))
                count += 1
                continue
        else:
            print("That isn't a valid crime. Try again!")
            continue
plot_data = [
go.Scatter(x=crime['Year'], y=crime[user_input], mode="lines+markers", name=(user_input), marker=dict(color='orange')),
]

py.iplot({ 'data': plot_data,
'layout': {
   'title': ("%s Over Time" % user_input),
   'xaxis': {
     'title': 'Year'},
   'yaxis': {
    'title': user_input}
}})

Enter the crime you'd like to track or type 'list' for a list of crimes. Type 'quit' to exit the program: Robbery

## Reminder of Evaluation Criteria

1. What the problem attempted (analysis, code, and answered questions) ?
2. What the problem analysis thought out? (does the program match the plan?)
3. Does the code execute without syntax error?
4. Does the code solve the intended problem?
5. Is the code well written? (easy to understand, modular, and self-documenting, handles errors)